import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from './ui/navbar-component';
import { Providers } from './providers';
const inter = Inter({ subsets: ['latin'] });
import { Provider } from './provider';
export const metadata: Metadata = {
    title: 'Task Manager',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <Provider>
                <body className={inter.className}>
                    <Providers>
                        <>
                            <Navbar />
                        </>
                        {children}
                    </Providers>
                </body>
            </Provider>
        </html>
    );
}
